export const GatewayErrorCode = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  CALLER_TOKEN_INVALID: 'CALLER_TOKEN_INVALID',
  CALLER_TOKEN_CLAIMS_INVALID: 'CALLER_TOKEN_CLAIMS_INVALID',
  CALLER_NOT_AUTHORIZED: 'CALLER_NOT_AUTHORIZED',
  OAUTH_NOT_CONFIGURED: 'OAUTH_NOT_CONFIGURED',
  AUTHORIZATION_CHECK_UNAVAILABLE: 'AUTHORIZATION_CHECK_UNAVAILABLE',
  AGENT_NOT_PUBLISHED: 'AGENT_NOT_PUBLISHED',
  OAUTH_CHANNEL_DISABLED: 'OAUTH_CHANNEL_DISABLED',
  AGENT_OAUTH_MISCONFIGURED: 'AGENT_OAUTH_MISCONFIGURED',
  IP_NOT_ALLOWED: 'IP_NOT_ALLOWED',
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  RUN_NOT_FOUND: 'RUN_NOT_FOUND',
  RUN_OWNERSHIP_MISMATCH: 'RUN_OWNERSHIP_MISMATCH',
  ENGINE_NOT_FOUND: 'ENGINE_NOT_FOUND',
  EXECUTION_ERROR: 'EXECUTION_ERROR',
  EXECUTION_TIMEOUT: 'EXECUTION_TIMEOUT',
  EXECUTION_INTERRUPTED: 'EXECUTION_INTERRUPTED',
  CONTEXT_LIMIT_EXCEEDED: 'CONTEXT_LIMIT_EXCEEDED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',
  AGENT_QUEUE_FULL: 'AGENT_QUEUE_FULL',
  AGENT_WORKSPACE_UNAVAILABLE: 'AGENT_WORKSPACE_UNAVAILABLE',
  AGENT_CONFIGURATION_ERROR: 'AGENT_CONFIGURATION_ERROR',
  PROVIDER_REAUTH_REQUIRED: 'PROVIDER_REAUTH_REQUIRED',
  PROVIDER_AUTH_FAILED: 'PROVIDER_AUTH_FAILED',
  PROVIDER_RATE_LIMITED: 'PROVIDER_RATE_LIMITED',
  PROVIDER_QUOTA_EXCEEDED: 'PROVIDER_QUOTA_EXCEEDED',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RUN_NOT_CANCELLABLE: 'RUN_NOT_CANCELLABLE',
  SESSION_BUSY: 'SESSION_BUSY',
} as const

export type GatewayErrorCode = (typeof GatewayErrorCode)[keyof typeof GatewayErrorCode]

export type GatewayErrorSource = 'caller' | 'agent' | 'provider' | 'platform'

export type GatewayErrorAction =
  | 'fix_request'
  | 'obtain_new_access_token'
  | 'use_allowed_network'
  | 'wait_for_current_run'
  | 'retry'
  | 'retry_later'
  | 'contact_agent_owner'
  | 'contact_platform_administrator'

export interface GatewayError {
  code: GatewayErrorCode
  message: string
  source?: GatewayErrorSource
  action?: GatewayErrorAction
  retryable?: boolean
  details?: unknown
}
