import { randomBytes } from 'node:crypto'

export const DEFAULT_PORT = 3502

/** 64-char hex string for AUTH_SECRET (matches `openssl rand -hex 32`). */
export function generateAuthSecret(): string {
  return randomBytes(32).toString('hex')
}

/**
 * Unique, stable Compose project name persisted per install. Without it,
 * Compose defaults the project name to the directory BASENAME — /srv/a/a2wave
 * and /srv/b/a2wave would resolve to the same `a2wave_a2wave-data` volume,
 * the second install would mount the first one's database, and either side's
 * `setup --down` (compose down -v) would delete the shared volume.
 */
export function generateProjectName(): string {
  return `a2wave-${randomBytes(4).toString('hex')}`
}

// Docker image reference charset (name[:tag][@digest]). Anything outside this
// (newlines, spaces, quotes, '#') could inject extra compose directives when
// interpolated into the generated YAML.
const IMAGE_REF_PATTERN = /^[a-z0-9]+(?:[._\-/:][a-zA-Z0-9._\-]+)*(?:@sha256:[a-f0-9]+)?$/

/** Reject image refs that are not a plain docker reference (YAML-injection guard). */
export function validateImageRef(ref: string): void {
  if (!IMAGE_REF_PATTERN.test(ref)) {
    throw new Error(
      `Invalid image reference: ${JSON.stringify(ref)}. Expected a plain docker image ref like ghcr.io/org/name:tag`,
    )
  }
}

export interface EnvFileInput {
  authSecret: string
  port: number
  /** External base URL of the instance, e.g. http://localhost:3502 */
  baseUrl: string
  /** Unique Compose project name (see generateProjectName) */
  projectName: string
  /** Container image; drives A2WAVE_IMAGE, which `setup --upgrade` rewrites. */
  image?: string
}

/**
 * Render the generated .env content for a fresh install.
 * Deliberately no ADMIN_PASSWORD: the admin password is set on first login via
 * the web setup screen or `a2wave setup` interactive prompt (POST /auth/setup),
 * so it never lands in a file or terminal scrollback.
 */
export function buildEnvFile(input: EnvFileInput): string {
  const lines = [
    '# Generated by `a2wave setup` — edit and `docker compose up -d` to apply.',
    '',
    '# Unique Compose project name. DO NOT change or remove: without it Compose',
    '# falls back to the directory basename, and two installs in same-named',
    '# directories would share (and on teardown, delete) the same data volume.',
    `COMPOSE_PROJECT_NAME=${input.projectName}`,
    '',
    '# Auth signing secret (keep private; rotating it invalidates all sessions)',
    `AUTH_SECRET=${input.authSecret}`,
    '',
    '# Host port the platform is exposed on',
    `A2WAVE_PORT=${input.port}`,
    '',
    '# Container image. `a2wave setup --upgrade` rewrites this line; changing it',
    '# by hand and running `docker compose up -d` has the same effect.',
    `A2WAVE_IMAGE=${input.image ?? ''}`,
    '',
    '# Browser origin allowed to call the API',
    `CORS_ORIGIN=${input.baseUrl}`,
  ]
  // Gateway signing only reaches its standards path (URL issuer + discovery)
  // over https, so only prefill the origin when the install is already https;
  // an http value would be accepted by env validation but rejected as an issuer.
  if (input.baseUrl.startsWith('https://')) {
    lines.push(
      '',
      '# External origin of this instance. Lets JWT-verifying gateways discover',
      '# the public key at /.well-known/jwks.json instead of being handed it.',
      `PUBLIC_URL=${input.baseUrl}`,
    )
  }
  if (input.baseUrl.startsWith('http://')) {
    lines.push(
      '',
      '# HTTP deployment: secure cookies would be dropped by the browser and',
      '# login would loop back to the login page. Set true once behind HTTPS.',
      'AUTH_COOKIE_SECURE=false',
    )
  }
  lines.push('')
  return lines.join('\n')
}

/**
 * Read the `A2WAVE_IMAGE` value from an install's .env, or null when absent.
 *
 * The image is a plain env key rather than a line inside docker-compose.yml
 * precisely so that reading and writing it needs no YAML understanding.
 */
export function readEnvImage(env: string): string | null {
  const raw = env.match(/^A2WAVE_IMAGE=(.*)$/m)?.[1]?.trim()
  if (!raw) return null
  // Strip surrounding quotes: a hand-written `A2WAVE_IMAGE="a2wave:1.0"` is a
  // valid env value, but keeping the quotes would surface a ref the operator
  // cannot paste into a docker command in the rollback messages.
  const unquoted = raw.replace(/^(['"])(.*)\1$/, '$2')
  return unquoted ? unquoted : null
}

/**
 * Return `env` with `A2WAVE_IMAGE` set to `image`, appending the key when it is
 * absent (an install predating the key) and leaving every other byte untouched.
 *
 * Only that one line may move: a regenerated AUTH_SECRET invalidates every
 * session, and a regenerated COMPOSE_PROJECT_NAME points Compose at a different
 * volume and orphans the database while still reporting success.
 */
export function replaceEnvImage(env: string, image: string): string {
  if (/^A2WAVE_IMAGE=.*$/m.test(env)) {
    return env.replace(/^A2WAVE_IMAGE=.*$/m, `A2WAVE_IMAGE=${image}`)
  }
  const separator = env.endsWith('\n') || env === '' ? '' : '\n'
  return `${env}${separator}A2WAVE_IMAGE=${image}\n`
}

/**
 * Point a legacy compose file's hardcoded `image:` at the A2WAVE_IMAGE variable.
 *
 * Installs generated before the image became an env key hardcode the ref, where
 * a new A2WAVE_IMAGE value is simply ignored — the upgrade would report success
 * while the container stayed on the old image.
 *
 * Deliberately does NOT search for "the a2wave service's image line". Locating
 * it means understanding YAML with regexes, and that is precisely what produced
 * six wrong-service rewrites before the image became a variable — each one
 * repointing a sidecar or a template while a2wave stayed stale. Instead this
 * recognises the exact single-service shape `buildComposeFile` emits, which is
 * the only file whose structure is known, and refuses everything else so the
 * operator makes the one-line edit themselves.
 *
 * Returns null when no migration is needed (already a variable); throws with the
 * exact edit to make when the file is not one this command generated.
 */
export function migrateComposeImageToVariable(compose: string): string | null {
  // "Already migrated" must mean the a2wave service's OWN image line uses the
  // variable — a whole-file substring check let a sidecar's env or a comment
  // mentioning the name skip the migration, leaving a2wave hardcoded while the
  // upgrade rewrote only .env and reported success on the old image.
  const alreadyMigrated =
    /^services:\r?\n[ \t]+a2wave:\r?\n[ \t]+image:[ \t]*\$\{A2WAVE_IMAGE[:\-}]/m
  if (alreadyMigrated.test(compose)) return null

  // The generated file declares exactly one service, `a2wave`, whose image is
  // an unquoted literal on its own line. Anything else — a second service, a
  // quoted value, an anchor block — is hand-edited and out of scope.
  const generated =
    /^services:\r?\n[ \t]+a2wave:\r?\n[ \t]+image:[ \t]*([^"'$\s#][^\s#]*)[ \t]*\r?$/m
  const match = compose.match(generated)
  // A second `image:` anywhere means another service, an anchor, or a template
  // — i.e. a file whose structure this command cannot vouch for.
  const imageCount = (compose.match(/^[ \t]*image:/gm) ?? []).length
  // Likewise a second service key: the generated file declares exactly one.
  // Walk the `services:` block explicitly and count only its direct children,
  // so nested keys like `ports:` / `volumes:` do not inflate the count.
  let inServices = false
  let serviceCount = 0
  // Depth of the service names themselves, learned from the first key inside
  // the block rather than assumed to be two spaces — `generated` accepts any
  // `[ \t]+`, so hardcoding two rejected files the rest of the check allows.
  let nameIndent: number | null = null
  for (const line of compose.split('\n')) {
    const trimmed = line.trimEnd()
    if (/^services:[ \t]*$/.test(trimmed)) {
      inServices = true
      continue
    }
    if (!inServices || trimmed === '') continue
    if (/^\S/.test(trimmed)) break // back at a top-level key: block ended
    const indent = trimmed.match(/^[ \t]*/)?.[0].length ?? 0
    if (nameIndent === null) nameIndent = indent
    if (indent === nameIndent && /:[ \t]*$/.test(trimmed)) serviceCount++
  }

  if (!match || imageCount !== 1 || serviceCount !== 1) {
    throw new Error(
      [
        'docker-compose.yml does not match the layout `a2wave setup` generates, so its image line cannot be migrated safely.',
        'Edit it by hand — change the a2wave service to read the image from .env:',
        '    image: ${A2WAVE_IMAGE:-<your current image>}',
        'then re-run the upgrade.',
      ].join('\n'),
    )
  }
  return compose.replace(generated, (line, ref: string) =>
    line.replace(`image: ${ref}`, `image: \${A2WAVE_IMAGE:-${ref}}`),
  )
}

export interface ComposeFileInput {
  image: string
  port: number
}

/**
 * Render a minimal docker-compose.yml for a public install.
 * Deliberately excludes internal-only settings (P4 SCM, IDaaS, provider CLI
 * home mounts) — advanced deployments should consult the docs instead.
 */
export function buildComposeFile(input: ComposeFileInput): string {
  return [
    'services:',
    '  a2wave:',
    // Variable, not a hardcoded ref: an upgrade then means writing one line in
    // .env instead of locating and rewriting this line, which required parsing
    // YAML with regexes and mis-targeted the wrong service in six distinct
    // valid-compose shapes. The generation-time ref stays as the fallback so
    // the file still works standalone.
    `    image: \${A2WAVE_IMAGE:-${input.image}}`,
    '    ports:',
    // Read the host port from .env so editing A2WAVE_PORT there actually works;
    // the generation-time port is only the fallback default.
    `      - "\${A2WAVE_PORT:-${input.port}}:3502"`,
    '    env_file:',
    '      - .env',
    '    environment:',
    '      - NODE_ENV=production',
    '      - PORT=3502',
    '      - DATABASE_URL=/app/data/a2wave.db',
    '      - A2WAVE_SKILLS_STORAGE=/app/data/skills',
    '    volumes:',
    '      - a2wave-data:/app/data',
    // Provider CLIs (Cursor / Codex / Claude Code / ...) persist localSession
    // state under the service HOME; without this volume every container
    // rebuild wipes those logins.
    '      - a2wave-cli-home:/home/appuser',
    '    restart: unless-stopped',
    '',
    'volumes:',
    '  a2wave-data:',
    '  a2wave-cli-home:',
    '',
  ].join('\n')
}
